### ISSUE TITLE
The real stuff

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/FladischerMichael.monit#1]
@meatric Üdvözöllek!
Ez a repó nem sokat ér.

Itt élnek az élő konfigok
https://github.com/szepeviktor/debian-server-tools/tree/master/monitoring/monit/services

És itt az install szkript hozzá (Debian alapú rendszerekhez)
https://github.com/szepeviktor/debian-server-tools/blob/master/monitoring/monit/monit-debian-setup.sh

Ha szükséges, segítek is.

**Comment by meatric** [comment]
@szepeviktor Szervusz,
Köszi a visszajelzést, akkor ezeket csillagozom :)
